// Update configs for your site here
export const SITE_CONFIG = {
    ROOT_URL: 'https://nhannguyendacoder.com',
    ROUTE: '',
    NAME: 'Nhan Nguyen Da Coder',
    TITLE: 'Nhan Nguyen Da Coder',
    DESC: 'Xin chào, mình là Nhân Nguyễn. Mình viết blog hướng dẫn lập trình web dành cho người tự học lập trình.',
    PORTFOLIO_DESC: 'I help companies develop high performance, scalable and maintainable Angular applications.',
    JOB_TITLE: 'Senior Angular Developer',
    IMAGE: 'https://nhannguyendacoder.com/assets/images/nhan-nguyen-da-coder.jpg',
    PORTFOLIO_IMAGE: 'https://nhannguyendacoder.com/assets/images/portfolio-thumb.png',
    KEYWORDS: 'tu hoc lap trinh, tu hoc lap trinh tu can ban, lap trinh',
    COPYRIGHT: `Copyright &copy; ${new Date().getFullYear()} <a target="_blank" href="https://www.facebook.com/NhanNguyenDaCoder">Nhan Nguyen Da Coder</a>. All Rights Reserved`,
    FANPAGE: 'https://www.facebook.com/NhanNguyenDaCoder',
    PROFILE: 'https://www.facebook.com/nhaancs',
    GROUP: 'https://www.facebook.com/groups/toituhoclaptrinhgroup',
    LINKEDIN: 'https://www.linkedin.com/in/nhaancs',
    PORTFOLIO: 'https://nhaancs.github.io',
    GITHUB: 'https://github.com/nhaancs',
    TWITTER: 'https://twitter.com/nhaancs',
    BLOG: 'https://nhannguyendacoder.com/blog',
    EMAIL: 'nhanpublic@gmail.com',
}